ALTER TABLE requests ADD COLUMN customer_id INTEGER;
ALTER TABLE requests ADD COLUMN provider_id INTEGER;
ALTER TABLE requests ADD COLUMN service_label TEXT;
ALTER TABLE requests ADD COLUMN origin_province TEXT DEFAULT 'تهران';
ALTER TABLE requests ADD COLUMN origin_city TEXT DEFAULT 'تهران';
ALTER TABLE requests ADD COLUMN origin_district TEXT;
ALTER TABLE requests ADD COLUMN origin_notes TEXT;
ALTER TABLE requests ADD COLUMN origin_property_type TEXT DEFAULT 'residential';
ALTER TABLE requests ADD COLUMN origin_lat REAL DEFAULT 35.7219;
ALTER TABLE requests ADD COLUMN origin_lng REAL DEFAULT 51.3347;
ALTER TABLE requests ADD COLUMN has_elevator INTEGER DEFAULT 1;
ALTER TABLE requests ADD COLUMN floor_number INTEGER DEFAULT 1;
ALTER TABLE requests ADD COLUMN needs_parts INTEGER DEFAULT 0;
ALTER TABLE requests ADD COLUMN urgency TEXT DEFAULT 'normal';
ALTER TABLE requests ADD COLUMN pricing_model TEXT DEFAULT 'fixed';
ALTER TABLE requests ADD COLUMN scheduled_date TEXT DEFAULT 'امروز';
ALTER TABLE requests ADD COLUMN scheduled_time TEXT DEFAULT 'فوری';
ALTER TABLE requests ADD COLUMN estimate_avg INTEGER DEFAULT 1800000;
ALTER TABLE requests ADD COLUMN final_price INTEGER;
ALTER TABLE requests ADD COLUMN insurance_tier_id TEXT DEFAULT 'gold_300m';
ALTER TABLE requests ADD COLUMN updated_at TEXT;
