const fs = require('fs');
let content = fs.readFileSync('worker.js', 'utf8');

content = content.replace(/<a href="\/services\/tasisat" class="([^"]*?)">(.*?)برق‌کشی و روشنایی(.*?)<\/a>/g, '<a href="/services/electrical" class="$1">$2برق‌کشی و روشنایی$3</a>');
content = content.replace(/<a href="\/services\/tasisat" class="([^"]*?)">(.*?)بازسازی و دکوراسیون(.*?)<\/a>/g, '<a href="/services/renovation" class="$1">$2بازسازی و دکوراسیون$3</a>');
content = content.replace(/<a href="\/services\/tasisat" class="([^"]*?)">(.*?)خدمات بنایی و عمرانی(.*?)<\/a>/g, '<a href="/services/construction" class="$1">$2خدمات بنایی و عمرانی$3</a>');

// Also fix the home page category cards
content = content.replace(/<a href="\/services\/tasisat" class="inline-flex items-center justify-center bg-white.*?>(.*?)تأسیسات ساختمان/s, '<a href="/services/tasisat" class="inline-flex items-center justify-center bg-white text-brand-500 w-12 h-12 rounded-2xl shadow-sm group-hover:bg-brand-500 group-hover:text-white transition-all transform group-hover:scale-110 mb-6">\n                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"></path></svg>\n                    </a>\n                    <h3 class="text-xl font-bold text-slate-800 mb-3 group-hover:text-brand-600 transition-colors">\n                        <a href="/services/tasisat" class="before:absolute before:inset-0">تأسیسات ساختمان</a>\n                    </h3>');

content = content.replace(/<a href="\/services\/tasisat" class="inline-flex items-center justify-center bg-white.*?>(.*?)برق‌کشی و روشنایی/s, '<a href="/services/electrical" class="inline-flex items-center justify-center bg-white text-brand-500 w-12 h-12 rounded-2xl shadow-sm group-hover:bg-brand-500 group-hover:text-white transition-all transform group-hover:scale-110 mb-6">\n                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>\n                    </a>\n                    <h3 class="text-xl font-bold text-slate-800 mb-3 group-hover:text-brand-600 transition-colors">\n                        <a href="/services/electrical" class="before:absolute before:inset-0">برق‌کشی و روشنایی');

content = content.replace(/<a href="\/services\/tasisat" class="inline-flex items-center justify-center bg-white.*?>(.*?)بازسازی و دکوراسیون/s, '<a href="/services/renovation" class="inline-flex items-center justify-center bg-white text-brand-500 w-12 h-12 rounded-2xl shadow-sm group-hover:bg-brand-500 group-hover:text-white transition-all transform group-hover:scale-110 mb-6">\n                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"></path></svg>\n                    </a>\n                    <h3 class="text-xl font-bold text-slate-800 mb-3 group-hover:text-brand-600 transition-colors">\n                        <a href="/services/renovation" class="before:absolute before:inset-0">بازسازی و دکوراسیون');

content = content.replace(/<a href="\/services\/tasisat" class="inline-flex items-center justify-center bg-white.*?>(.*?)خدمات بنایی و عمرانی/s, '<a href="/services/construction" class="inline-flex items-center justify-center bg-white text-brand-500 w-12 h-12 rounded-2xl shadow-sm group-hover:bg-brand-500 group-hover:text-white transition-all transform group-hover:scale-110 mb-6">\n                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"></path></svg>\n                    </a>\n                    <h3 class="text-xl font-bold text-slate-800 mb-3 group-hover:text-brand-600 transition-colors">\n                        <a href="/services/construction" class="before:absolute before:inset-0">خدمات بنایی و عمرانی');

// In footer (Island 2)
// The regexes above already handle the footer links!

fs.writeFileSync('worker.js', content);
console.log('Links updated');
